### ISSUE TITLE
Black & white (grayscale?) image generates palette with colors

### ISSUE THREAD

**Issue by rayshan** [jariz/vibrant.js#18]
Hi, default params with this image:
https://www.facebook.com/photo.php?fbid=10107296866472911&l=bb741fb5ef

Generates these results:

![screen shot 2015-08-07 at 4 45 01 pm](https://cloud.githubusercontent.com/assets/3760840/9147946/115dc060-3d24-11e5-8c5f-10a5a095981f.png)

It would be nice to auto detect if an image is B&W and only generate a palette on the grayscale.

**Comment by michaltaberski** [comment]
Yes, I have the same problem. Did you figure it out @rayshan ?

**Comment by rayshan** [comment]
No. Basically vibrant algorithm doesn't support this. I switched to `node-vibrant` and had a discussion with the author there:
https://github.com/akfish/node-vibrant/issues/16

I'm using a workaround by manually detecting grayscale images:
https://github.com/rayshan/cartier/blob/b7b8720171eec81494dd9db0d974c536455b4d4c/tasks/metadata.js#L35

**Comment by michaltaberski** [comment]
Thanks for replay. I end up with: https://github.com/lokesh/color-thief works well with B&W images.

**Comment by jariz** [comment]
@michaltaberski Keep in mind that color thief gets the most used colors, not the most vibrant ones.

**Comment by pugson** [comment]
Has anybody managed to solve this issue in a fork?

**Comment by jariz** [comment]
Don't run vibrant on B&W images.
wontfix.
