### ISSUE TITLE
How to import Vibrant using jspm

### ISSUE THREAD

**Issue by jdwillemse** [jariz/vibrant.js#19]
I'm including Vibrant in my project using JSPM. I get the following error
`Error: Error loading "quantize" at file:/path/to/project/folder/quantize.js`

Do you know what might be the issue?

**Comment by jariz** [comment]
Have you tried using the [npm version](https://github.com/akfish/node-vibrant)?

**Comment by jdwillemse** [comment]
Yes. I dont get the error, but when I dump `swatches` the output is always undefined:

```
DarkMuted: undefined
DarkVibrant: undefined
LightMuted: undefined
LightVibrant: undefined
Muted: undefined
Vibrant: undefined
```
