### ISSUE TITLE
Demo not working in Safari or Firefox

### ISSUE THREAD

**Issue by sgwilym** [jariz/vibrant.js#21]
Trying out vibrant.js in the jsfiddle on the webpage fails, returning the follow error:
`/TypeError: cmap.vboxes is undefined`

Edit: just noticed the disclaimer regarding image dropping only working in Chrome. Why is this the case?

**Comment by randohinn** [comment]
And also doesn't work with Chrome, but that gives an error like #37.

**Comment by mcgraphix** [comment]
Chome on Mac Sierra gives this error when dropping an image on the demo at http://jariz.github.io/vibrant.js/:

````
Uncaught TypeError: Cannot read property 'map' of undefined
    at new Vibrant (http://cdn.rawgit.com/jariz/vibrant.js/master/dist/Vibrant.js:43:35)
    at FileReader.progress (coffeescript:24:19)
````

**Comment by kjellouli** [comment]
Same error here.. Do you have any news about this issue ?

**Comment by akfish** [comment]
vibrant.js is deprecated. Please try [node-vibrant](https://github.com/akfish/node-vibrant) instead and see if this issue persists. You are welcome to submit an issue there if that's the case.
