### ISSUE TITLE
Color does not look right

### ISSUE THREAD

**Issue by anhquancao** [jariz/vibrant.js#27]
I am trying your library with this image and the colors does not look right, especially the yellow color. Could you please explain to me why this happen?

<img width="948" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9668858/19624930/501c9fac-9934-11e6-9630-3e8931b530eb.png">
![1477210243mtzdjveyisca2fl](https://cloud.githubusercontent.com/assets/9668858/19624931/5512f07e-9934-11e6-97e1-9e13d7e90a6f.jpg)

**Comment by jariz** [comment]
See my response on #30
