### ISSUE TITLE
Vibrant.js + masterslider

### ISSUE THREAD

**Issue by Shnalla** [jariz/vibrant.js#28]
Hi, 

I'm trying to use vibrant.js with masterslider.
The "issue" is that Masterslider uses data-src attributes 

`<img src="images/blank.gif')" data-src="path-to-my-image" alt="alt text">`

I'm only able to retrieve blank.gif

**Comment by jariz** [comment]
Having a quick read through their docs, it seems lke they added the 'data-src' property to prevent all images being loaded in at once.
So yea, they do switch the data-src back to the src attr at some point.
It seems like there are [a couple events you can hook](http://masterslider.com/doc/#api) (with CHANGE_START looking like what you need).
If you hook vibrant to the next slide at that event, it should probably work.

Hope I've helped you, I don't really see this as an issue with Vibrant itself, so I'll close this now.
