### ISSUE TITLE
Incorrect Analysis

### ISSUE THREAD

**Issue by Undistraction** [jariz/vibrant.js#30]
For [this image](https://dl.dropboxusercontent.com/u/316978/vangogh/images/child_with_orange-747.jpg), Vibrant completely misses the blue:

![cap copy](https://cloud.githubusercontent.com/assets/161489/22878533/171e56e0-f1d2-11e6-9d16-4a0264d2327b.jpg)

**Comment by jariz** [comment]
It works with most images, but like any algorithm, you're gonna have a few cases where it misses out. I don't really think this is a issue (with a clear solution, at least).
So I'm gonna close this.
