### ISSUE TITLE
Gulpfile's compilerPath is hardcoded to a path that doesn't exist

### ISSUE THREAD

**Issue by iMerica** [jariz/vibrant.js#31]
By default, doing a `bower install` (as per your build steps) doesn't bring down the compiler at `bower_components/closure-compiler/lib/vendor/compiler.jar` like the gulp file refers to. This means the build steps are currently broken without updating the gulpfile manually.

**Comment by akfish** [comment]
vibrant.js is deprecated. Please use [node-vibrant](https://github.com/akfish/node-vibrant) instead. This issue should not exist in node-vibrant due to different implementation.
