### ISSUE TITLE
UMD / Publish to npm

### ISSUE THREAD

**Issue by btholt** [jariz/vibrant.js#4]
Hi friend!

I'm working on getting this into my project (as it is the missing link to getting working; thank you so much!) and I noticed it's not published to npm. I'll probably work it so I can use it personally as an npm module; do you have any interest in using the [UMD format](https://github.com/umdjs/umd) so that your module can be consumed by both Bower and npm users?

**Comment by btholt** [comment]
Also, though I understand this isn't your target, this doesn't seem to work out of the box with [deamdify](https://github.com/jaredhanson/deamdify) / [debowerify](https://github.com/eugeneware/debowerify).

Just so you know. :smiley:

**Comment by jariz** [comment]
Hey, maybe I'm not smart enough, but I'm not entirely sure what you mean, can you file a pull request?

**Comment by sshrshnv** [comment]
+1
@jariz, create and publish package to npm, please

**Comment by btholt** [comment]
I'm happy to take a shot at it. It'll just make it so every time you publish to Bower you'll have to remember to publish to npm too.

**Comment by matthieuh** [comment]
+1

**Comment by akfish** [comment]
If anyone is looking for a node.js port, here's my implementation: [node-vibrant](https://github.com/akfish/node-vibrant).
It's modified from this project and works on server-side.

**Comment by jariz** [comment]
@akfish wow that's pretty cool. especially because it's actually compatible with node while me moving this project to some universal format would still leave the 'it only works on browsers' problem 
So, thanks. I'll add your project to the readme!

**Comment by akfish** [comment]
A little update. 
`node-vibrant` now supports browser & browserify with identical API for all platforms. I thought this might be what this issue is originally about. Just so you know. :)

**Comment by btholt** [comment]
It is. Awesome. Thank you.
