### ISSUE TITLE
canvas added in the body 

### ISSUE THREAD

**Issue by amirping** [jariz/vibrant.js#45]
I'am using vibrant.js with angular 4 , and exprience an issues that the canvas didn't removed from the body 
![image](https://user-images.githubusercontent.com/3626339/31047575-beae68ba-a60d-11e7-8cba-aa7ae79f93bf.png)
 and i call it like that 
`

    let v = new Vibrant(changes.toPlayRadio.currentValue.pic);
    v.getPalette((err, palette) => {
      var rgb = palette.Vibrant.getRgb()
      this.radioBackground =
      {
        'background' : 'rgb('+rgb[0]+','+rgb[1]+','+rgb[2]+');'
      }
    });
  `

**Comment by LekoArts** [comment]
@amirping

I also got this issue. Did you resolve it? :/

**Comment by LekoArts** [comment]
@jariz Any idea?
When I switch pages the canvas doesn't get removed

**Comment by jariz** [comment]
1. If the canvas doesn't get cleaned up, it's likely because vibrant crashed.
2. You're ignoring the error in your code example.

**Comment by LekoArts** [comment]
Actually I found the solution I think:
https://github.com/akfish/node-vibrant/pull/46

Sadly he/she isn't maintaining the package anymore and therefore this PR won't be merged anytime soon.

**Comment by akfish** [comment]
Hi, developer of node-vibrant here.
I'm back actively maintaining node-vibrant again. @jariz and I decided to deprecate vibrant.js.
This issue is fixed in [node-vibrant](https://github.com/akfish/node-vibrant). Please try it out. :)
