### ISSUE TITLE
Compatibility / Fallbacks

### ISSUE THREAD

**Issue by NickColley** [jariz/vibrant.js#5]
This is a really neat project, is there a decent way to detect if vibrant.js will work on a page?

I'm thinking in browsers that don't support canvas etc there could be a flag set so you can feature detect and such.

**Comment by jariz** [comment]
Wouldn't it be easier to just use [modernizr](http://modernizr.com/) if you have to support legacy browsers? Vibrant wasn't made for legacy browsers, and I have no plans to do so.

**Comment by NickColley** [comment]
That requires the user of vibrant.js to know what features are used that they'd need to detect.

Maybe if there was just a bit in the README of what's used then they could use modernizr on their own I guess?
