### ISSUE TITLE
Remote Images?

### ISSUE THREAD

**Issue by Benny-Afriat** [jariz/vibrant.js#6]
Is it possible to use this great tool on images from another domain?
of course after they have been loaded.

**Comment by jariz** [comment]
Sadly because of it using canvas, it requires the image to be on the same server, so you'll either have to proxy it or make sure the server passes the Access-Control-Allow-Origin header with your hostname.

**Comment by matthieuh** [comment]
For CORS img.setAttribute('crossOrigin', 'anonymous') does the trick !

**Comment by Benny-Afriat** [comment]
@jariz can you confirm that?
will this work?

**Comment by jariz** [comment]
Yes, just tested this and it does work. It can't be added to vibrant however, because vibrant expects the image to be loaded already. So simply add the attribute to the image (either programmatically or through html), add the 'load' event listener like normal and you're good to go.

I'll add this to the docs as a suggestion.

**Comment by ivana-helvin** [comment]
@jariz please give the example code of adding load event listener. I integrated with instagram photo.

**Comment by jariz** [comment]
Uhh, this is 101 javascript, but something like
```html
<img src="http://example.org/test.jpg" crossOrigin="anonymous">
```

```javascript
document.querySelector("img").addEventListener("load", function() { 
     // do your vibrant stuff here.
});
```

should do the trick

**Comment by ivana-helvin** [comment]
thanks!

**Comment by yarnball** [comment]
This is a great repo! But I to am having this issue. 


I cannot send the `crossOrigin="anonymous"` on my `<img` attribute as gets rejected by some servers. So I tried the `setAtrribute` but that didnt work either.

It seems to add the attribute, but I still get the error (line 10)

Any suggestions?

Running code:
https://codesandbox.io/s/1jwL9vvEZ

**Comment by jariz** [comment]
@yarnball No. You will have to ask the webmaster to enable CORS on the images, or rehost them yourself, there's sadly no other solution.

**Comment by yarnball** [comment]
@jariz thanks for that. just quickly, how do I choose which color to use as the response? Your example logs a varying number (eg Vibrant, Muted etc). How do I say specifically only return `vibrant` for example?

Doing the below code always gets the last hex in the swatch:

```
  matchCols = () => {
    const img = document.getElementById("favicon");
    var vibrant = new window.Vibrant(img);
    var swatches = vibrant.swatches();
    for (var swatch in swatches)
      if (swatches.hasOwnProperty(swatch) && swatches[swatch])
    this.setState({
      color: (swatch, swatches[swatch].getHex())
    });
        // console.log(swatch, swatches[swatch].getHex());
  };
```
