### ISSUE TITLE
Color post processing?

### ISSUE THREAD

**Issue by Pupix** [jariz/vibrant.js#9]
Hello!

While watching the I/O's "Material now" presentation this year I've noticed that from an album art they got the primary/accent color using Palette.

![mac miller](https://cloud.githubusercontent.com/assets/4929965/8003753/8d7ce3fa-0b7a-11e5-866d-abdccc6339e3.png)

When I tried to do the same using vibrant.js the colors they got are nowhere to be found. 

![mac miller 2](https://cloud.githubusercontent.com/assets/4929965/8003752/8d7b5864-0b7a-11e5-9c1f-edf041bac962.png)

Is it just a further post processing provided by the player app or should vibrant.js return the right colors using the [Material Pelette](http://www.google.com/design/spec/style/color.html#color-color-palette)?

**Comment by jariz** [comment]
Vibrant isn't an exact copy of Palette. I'm satisfied with it's results, and I don't really see it as an issue.
But if somebody wants to improve it to be more matching with the 'real thing' then they can go ahead and send a PR.
For 1:1 results check out the sweet [Material Palette Generator](http://marijnvdwerf.github.io/material-palette/) by @marijnvdwerf.

![](https://i.imgur.com/mxLKFRr.png)

**Comment by marijnvdwerf** [comment]
I think the colours used in sample imagery is not really generated by Pallete. Those bright blue and red don't even appear in the artwork in the "screenshot", let alone being able to survive Pallette's algorithm.

**Comment by Pupix** [comment]
@marijnvdwerf They do not appear directly indeed, but the artwork has shades of red/blue in it. That's why I think there's some kind of post processing going on, trying to match the raw colors to the palette (500 for red and A700 for blue)

@jariz It was just a question, not an issue. GitHub doesn't allow users to tag their issues (at least I haven't been able to find out how).

**Comment by jariz** [comment]
I think it just grabs a random color from the material color scheme for the secondary color. (maybe using the image as seed or something to make sure the generated colors stay the same)
Or it's just hardcoded :stuck_out_tongue:

**Comment by marijnvdwerf** [comment]
Also, if you're able to use PHP, I recommend https://github.com/marijnvdwerf/material-palette-php. I'm way better in PHP than in JS, and I was able to port this fairly easily. It's based on the latest version of the Android library, and should (technically) offer closer results.
